[package]
name = "futarchy_markets"
edition = "2024"
license = "BSL"

[dependencies]
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }

[addresses]
futarchy_markets = "0x4ef303a9f28a6c1e1a583837f0244a7000e550fbc2ccb16f7d46db6f8eb70140"
futarchy_one_shot_utils = "0x3dda2b29c33b794ca04f89dfeba1db2a3642bc68370a1fd9b8110126e1b74645"