[package]
name = "futarchy_markets"
edition = "2024"
license = "BSL"

[dependencies]
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_seal_utils = { local = "../futarchy_seal_utils" }
[addresses]
futarchy_markets  = "0x0"
futarchy_types  = "0x0"
futarchy_one_shot_utils  = "0x0"
futarchy_core  = "0x0"
futarchy_seal_utils  = "0x0"
