# Frontend Service Configuration
[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd frontend && pnpm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd frontend && pnpm run build-frontend"]

[staticAssets]
enabled = "true"
dir = "frontend/dist/client"

[start]
cmd = "npx serve -s frontend/dist/client -l 3000"

[variables]
NODE_ENV = "production"