# Backend Service - Simple and Sweet
[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "cd backend && pnpm install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "echo 'Backend build complete'"
]

[start]
cmd = "cd backend && pnpm start:railway"

[variables]
NODE_ENV = "production"