# Backend Service Configuration
[phases.setup]
nixPkgs = ["nodejs_18", "pnpm", "sqlite"]
aptPkgs = ["fonts-liberation", "fontconfig", "fonts-dejavu-core", "fonts-noto"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "fc-cache -fv",
    "cd backend && pnpm install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "echo 'Build phase complete - database setup will happen at startup'"
]

[start]
cmd = "cd backend && pnpm start:railway"

[variables]
NODE_ENV = "production"
PORT = "3000"