[package]
name = "futarchy_legal_actions"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountExtensions = { local = "../move-framework/packages/extensions" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets = { local = "../futarchy_markets" }
futarchy_multisig = { local = "../futarchy_multisig" }
futarchy_vault = { local = "../futarchy_vault" }
futarchy_lifecycle = { local = "../futarchy_lifecycle" }
Walrus = { local = "../walrus_walrus" }
WAL = { local = "../walrus_wal" }
[addresses]
futarchy_legal_actions = "0x0"
futarchy_one_shot_utils = "0xb839ca53f93fb215430bdc1f187cebb7cc1abab7282f695ca6969fc4303808aa"
futarchy_types = "0x9cd90e1b5ee92d9899f6bb22c2f822a9dfab88eca319d3719623156033276ab2"
futarchy_core = "0x243466b0c2002e092f40b71ac606578df2a958f87765c48d0edf4cecc417cd8c"
futarchy_markets = "0x7b6c4e2939cf538432320b1b91a2d8119ef1f37ec81281c04002d3d746bfba8f"
futarchy_vault = "0x4543a8909a024b17338bee7a3468ed0b978811f2df4aba09da96cb18a3ed8682"
futarchy_multisig = "0xaf50964aa3d534640f7ce32c180955c883a657fb6875d4b41687b280b8d52704"
futarchy_lifecycle = "0x17a4009b31659977cfd0156c2bf06aef1db924ff2b5109b0f6d692e7c4bb2e7f"
account_protocol = "0xc24e7496e469de4fc9aa52205b0c69195e23d913db19dede6ded8dd77d9e36d0"
account_extensions = "0x0845277c95d7b28ea5d0b3ee653b679e4d4c8649ec299f4f4f5cec4141aa2dbe"
