[package]
name = "AccountExtensions"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies]

[addresses]
account_extensions = "0x87bee60d3ea6dc5b42e1074134373af27733fb3c5ebc3ac8e013901426d85d53"