[package]
name = "futarchy_lifecycle"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountExtensions = { local = "../move-framework/packages/extensions" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets = { local = "../futarchy_markets" }
futarchy_vault = { local = "../futarchy_vault" }
futarchy_multisig = { local = "../futarchy_multisig" }
futarchy_streams = { local = "../futarchy_streams" }
# futarchy_factory = { local = "../futarchy_factory" } # Moved to governance_actions
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_lifecycle  = "0x0"
futarchy_types  = "0x0"
futarchy_one_shot_utils  = "0x0"
futarchy_core  = "0x0"
futarchy_markets  = "0x0"
futarchy_vault  = "0x0"
futarchy_multisig  = "0x0"
futarchy_streams  = "0x0"
# futarchy_factory  = "0x0" # Moved to governance_actions
account_protocol = "0xc24e7496e469de4fc9aa52205b0c69195e23d913db19dede6ded8dd77d9e36d0"
account_extensions = "0x0845277c95d7b28ea5d0b3ee653b679e4d4c8649ec299f4f4f5cec4141aa2dbe"
account_actions = "0x59feeec832fb397c7e4fc80eff70da6e675c2e9b31eda830e8a179dfaede9d30"
