[package]
name = "futarchy_one_shot_utils"
edition = "2024"
license = "BSL"

[dependencies]

[addresses]
futarchy_one_shot_utils = "0x6f37d232d20f2ff1f6d30e7eccc8ea77955fb1bd85a67f26169d96672c878839"
