[package]
name = "FutarchyActions"
edition = "2024.beta"
license = "Apache-2.0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }

[addresses]
# Production address will be generated when package is published
# For now, using development address
futarchy_actions = "0x1000"

# Standard library addresses
std = "0x1"
sui = "0x2"

# Account protocol addresses (these are the actual published addresses)
account_protocol = "0x10c87c29ea5d5674458652ababa246742a763f9deafed11608b7f0baea296484"
account_extensions = "0x87bee60d3ea6dc5b42e1074134373af27733fb3c5ebc3ac8e013901426d85d53"
account_actions = "0xf477dbfad6ab1de1fdcb6042c0afeda2aa5bf12eb7ef42d280059fc8d6c36c94"

