[package]
name = "futarchy_actions"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountExtensions = { local = "../move-framework/packages/extensions" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets = { local = "../futarchy_markets" }
futarchy_multisig = { local = "../futarchy_multisig" }
futarchy_vault = { local = "../futarchy_vault" }
futarchy_lifecycle = { local = "../futarchy_lifecycle" }
futarchy_specialized_actions = { local = "../futarchy_specialized_actions" }

[addresses]
futarchy_actions = "0x0"
account_protocol = "0x30448780c44b209898af12419ca4264f2f016c44b66da47d15739fa8a39aa772"
account_extensions = "0x18d76db190917de8d07775e5d196c296419f8de05b6e57924fc8e5e755f590f6"
account_actions = "0x37b9e21647615db8d522b2ae25495663834fb72de41c10057bfbb919446abdc3"
futarchy_one_shot_utils = "0x3dda2b29c33b794ca04f89dfeba1db2a3642bc68370a1fd9b8110126e1b74645"
futarchy_core = "0xb56da75c850e9e7db23156d975060638b322d117863a143d717bc7df03b1d927"
futarchy_markets = "0x4ef303a9f28a6c1e1a583837f0244a7000e550fbc2ccb16f7d46db6f8eb70140"
futarchy_multisig = "0x0"
futarchy_vault = "0x43770925f64b0265bf2da5a039c003b2b183537c872f9313936fb9c70e7348eb"
futarchy_lifecycle = "0x0"
futarchy_specialized_actions = "0x0"
