[package]
name = "futarchy_markets_operations"
edition = "2024"
license = "BSL"

[dependencies]
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_primitives = { local = "../futarchy_markets_primitives" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }

[addresses]
futarchy_markets_operations = "0x100a1e05969cefd523727b43c916f1e2d209e8efc2e09888d80e81335f2fbeba"
futarchy_markets_core = "0x5dbf784bd4b4c08572cbbcc760e0c29cafbb110534fb088029c3e7d1c30f6816"
futarchy_markets_primitives = "0x402cc5fc2eba359fd417d4cda419dc943fa5c2be4f9f54edf4b15353755232dc"
futarchy_types = "0xb413174c17d48ce1dc02f433dfd3bea87bf9d869d20727127abebf8a4cfd9ec5"
futarchy_one_shot_utils = "0x7e7d952d7668c969d6f20b68ccfae73a4ea510906aafc1e78b81d0cd1edecba0"
futarchy_core = "0x663c46a7d94c6255ac0026f5d333ff102c47648596734b5eb303c9491f6eef2b"
