[package]
name = "futarchy"
edition = "2024"
license = "BSL"

[dependencies]
futarchy_utils = { local = "../futarchy_utils" }
AccountExtensions = { local = "../move-framework/packages/extensions" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
AccountActions = { local = "../move-framework/packages/actions" }

[addresses]
# Production addresses will be generated when packages are published
# For now, using development addresses
futarchy = "0x0"
futarchy_utils = "0xebdffb8f5ef2415093491c9c3e80f14731d7022574b6e196f0a0c6446078103c"

# Account protocol addresses (these are the actual published addresses)
account_protocol = "0x3524efaf502bb2f845416b1cd73c97bd6130a6f28db9384c55c40b358cf96870"
account_extensions = "0x32b220eb8e08ffb4a9e946bdbdd90af6f4fe510f121fed438f3f1e6531eae7dd"
account_actions = "0x56cdad1b3e1135d97ac713f69e3d23a7dbbcf6500711b4bb71cbdff46e274491"

# When publishing to production:
# 1. First publish futarchy_actions package - get its address
# 2. Update futarchy_actions address here
# 3. Then publish futarchy package - get its address  
# 4. Update both packages with their production addresses





