[package]
name = "Kiosk"
version = "0.0.1"
# published-at = "0x0"
# published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "b5633abb4177" }

[addresses]
kiosk = "0xe6cb38323ad6d2fcdb4b0ed7c46e98a5619a1972de62e78d11826ac1b2bc55bf"
