name: Deploy to Railway Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'testnet-dev'
        type: choice
        options:
          - testnet-dev
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event.issue.pull_request && 
       contains(github.event.comment.body, '/deploy dev') && 
       github.event.comment.author_association == 'MEMBER')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
        run: |
          railway up --service backend --environment testnet-dev

      - name: Comment on PR
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Deployment to testnet-dev initiated!'
            })