[package]
name = "futarchy_factory"
edition = "2024.beta"
published-at  = "0x0"

[dependencies]
AccountExtensions = { local = "../move-framework/packages/extensions" }
AccountActions = { local = "../move-framework/packages/actions" }
futarchy_one_shot_utils = { local = "../futarchy_one_shot_utils" }
futarchy_types = { local = "../futarchy_types" }
futarchy_core = { local = "../futarchy_core" }
futarchy_markets_core = { local = "../futarchy_markets_core" }
futarchy_markets_operations = { local = "../futarchy_markets_operations" }
futarchy_vault = { local = "../futarchy_vault" }
futarchy_multisig = { local = "../futarchy_multisig" }
futarchy_oracle = { local = "../futarchy_oracle" }
futarchy_seal_utils = { local = "../futarchy_seal_utils" }
AccountProtocol = { local = "../move-framework/packages/protocol" }
[addresses]
futarchy_factory = "0x76b65095ea99b4dd4908b51c4649bf6c294141f21979587ae6b15c993d6daf8a"
futarchy_types = "0x022500182f96f1aa94c126fdf35c8063c7e9be368dbbfb065faefef401b8eb25"
futarchy_one_shot_utils = "0x0f6cb09aea285a7f696141baa758b3525db65d821885e86804238ec66047f508"
futarchy_core = "0x2dbaa2eb250746a6e0f787b3c212986ca6b4f15478cf56aaef2f4e477f19bf32"
futarchy_markets_core = "0x0"
futarchy_markets_operations = "0x0"
futarchy_vault = "0x6b87e5ab293c702984c61f31e2af1fa78ec4439e63caf6e0c8fc5e99be99d064"
futarchy_multisig = "0x8e216aa2f6eebad3377ac799c966d076c82dc9f58eccccbbf63bf28b206bc1cb"
futarchy_oracle = "0x772f010aa6957c875b5777a9e770e4f8e9c45a932e7e5fced33b2956095313ea"
futarchy_seal_utils = "0x82844122f7e106439b87948ea938a7a043273f90ec409e0c02b201c7281b55e2"
account_protocol = "0xaa8cdc1c3fc33ad6076270c79d626923fb21cd71a7881d4564ee1c4f22e7ba0a"
account_extensions = "0xa9ca20a7a38f897b021b35147070b3997e236c8b6791d6f115e264f3bb67ccd4"
